package main

import (
	"context"
	"log"
	"time"

	"medieval-store/config"
	"medieval-store/models"

	"github.com/joho/godotenv"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

func main() {
	// 1. Load the .env file from the root directory
	if err := godotenv.Load(); err != nil {
		log.Println("Warning: No .env file found or couldn't load it")
	}

	// 2. Connect to MongoDB using your existing config
	if err := config.ConnectMongo(); err != nil {
		log.Fatalf("Database connection failed: %v", err)
	}

	collection := config.MongoClient.Database("medieval_store").Collection("products")
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// 3. Optional: Clear existing products so you can run this script safely multiple times
	_, err := collection.DeleteMany(ctx, bson.M{})
	if err != nil {
		log.Fatalf("Failed to clear existing products: %v", err)
	}
	log.Println("Cleared old product data...")

	// 4. Create the Mock Data using your exact Struct
	mockProducts := []interface{}{
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Broadsword of the Bear",
			Model:        "SWD-001",
			SerialNumber: "SN-99812",
			Description:  "A heavy, two-handed broadsword forged from high-carbon steel. Excellent for close-quarters combat.",
			Quantity:     15,
			Price:        250.00,
			Discount:     0,
			Warranty:     "Lifetime (Against dragon fire)",
			Distributor:  "Ironhelm Forge",
			Category:     "Weapons",
			ImageURL:     "https://placeholder.com/broadsword.jpg",
			Tags:         []string{"sword", "melee", "heavy"},
			Rating:       4.8,
			ReviewCount:  24,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Scroll of Lesser Healing",
			Model:        "SPL-104",
			SerialNumber: "SN-11002",
			Description:  "A parchment inscribed with ancient runes. Instantly heals minor cuts and bruises when read aloud.",
			Quantity:     100,
			Price:        15.50,
			Discount:     10.0, // 10% off
			Warranty:     "No refunds once unsealed",
			Distributor:  "The Arcane Order",
			Category:     "Spells",
			ImageURL:     "https://placeholder.com/scroll.jpg",
			Tags:         []string{"magic", "healing", "consumable"},
			Rating:       4.2,
			ReviewCount:  156,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Elven Cloak of Hiding",
			Model:        "AMR-045",
			SerialNumber: "SN-44332",
			Description:  "A lightweight cloak that shifts color to match your surroundings. Currently out of stock due to high demand.",
			Quantity:     0, // Perfect for testing your out-of-stock logic!
			Price:        500.00,
			Discount:     0,
			Warranty:     "1 Year",
			Distributor:  "Rivendell Textiles",
			Category:     "Apparel",
			ImageURL:     "https://placeholder.com/cloak.jpg",
			Tags:         []string{"stealth", "armor", "rare"},
			Rating:       5.0,
			ReviewCount:  8,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		// --- WEAPONS ---
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Ranger's Longbow",
			Model:        "BOW-088",
			SerialNumber: "SN-77210",
			Description:  "Crafted from flexible yew wood. Includes a quiver of 20 iron-tipped arrows.",
			Quantity:     45,
			Price:        120.00,
			Discount:     0,
			Warranty:     "6 Months (String replacement only)",
			Distributor:  "Woodland Fletchers",
			Category:     "Weapons",
			ImageURL:     "https://placeholder.com/longbow.jpg",
			Tags:         []string{"bow", "ranged", "wood"},
			Rating:       4.6,
			ReviewCount:  89,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Obsidian Dagger",
			Model:        "DAG-012",
			SerialNumber: "SN-99100",
			Description:  "A sleek, razor-sharp dagger forged from volcanic glass. Perfect for rogues.",
			Quantity:     8,
			Price:        350.00,
			Discount:     5.0,
			Warranty:     "No Warranty (Fragile)",
			Distributor:  "Shadow Traders",
			Category:     "Weapons",
			ImageURL:     "https://placeholder.com/dagger.jpg",
			Tags:         []string{"dagger", "stealth", "melee"},
			Rating:       4.9,
			ReviewCount:  12,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Heavy Halberd",
			Model:        "HLB-044",
			SerialNumber: "SN-33112",
			Description:  "A versatile polearm featuring an axe blade topped with a spike.",
			Quantity:     20,
			Price:        180.00,
			Discount:     0,
			Warranty:     "2 Years",
			Distributor:  "Ironhelm Forge",
			Category:     "Weapons",
			ImageURL:     "https://placeholder.com/halberd.jpg",
			Tags:         []string{"polearm", "heavy", "melee"},
			Rating:       4.1,
			ReviewCount:  34,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Dwarven Crossbow",
			Model:        "CBW-001",
			SerialNumber: "SN-88221",
			Description:  "A mechanical marvel that fires bolts with devastating piercing power.",
			Quantity:     12,
			Price:        400.00,
			Discount:     15.0,
			Warranty:     "5 Years (Mechanical parts only)",
			Distributor:  "Deep Mountain Guild",
			Category:     "Weapons",
			ImageURL:     "https://placeholder.com/crossbow.jpg",
			Tags:         []string{"ranged", "mechanical", "dwarven"},
			Rating:       4.7,
			ReviewCount:  56,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},

		// --- APPAREL & ARMOR ---
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Standard Iron Chainmail",
			Model:        "AMR-101",
			SerialNumber: "SN-55441",
			Description:  "Basic but reliable protection against slashing attacks. Weighs 40 lbs.",
			Quantity:     30,
			Price:        200.00,
			Discount:     0,
			Warranty:     "1 Year",
			Distributor:  "Ironhelm Forge",
			Category:     "Apparel",
			ImageURL:     "https://placeholder.com/chainmail.jpg",
			Tags:         []string{"armor", "iron", "heavy"},
			Rating:       3.8,
			ReviewCount:  112,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Mithril Chestplate",
			Model:        "AMR-999",
			SerialNumber: "SN-00001",
			Description:  "Incredibly rare armor that is as light as a feather but harder than dragon scales.",
			Quantity:     1, // Low stock edge case!
			Price:        5000.00,
			Discount:     0,
			Warranty:     "Lifetime",
			Distributor:  "Deep Mountain Guild",
			Category:     "Apparel",
			ImageURL:     "https://placeholder.com/mithril.jpg",
			Tags:         []string{"armor", "legendary", "lightweight"},
			Rating:       5.0,
			ReviewCount:  2,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Hardened Leather Bracers",
			Model:        "AMR-022",
			SerialNumber: "SN-11223",
			Description:  "Provides decent wrist and forearm protection without sacrificing mobility.",
			Quantity:     85,
			Price:        45.00,
			Discount:     0,
			Warranty:     "30 Days",
			Distributor:  "Woodland Fletchers",
			Category:     "Apparel",
			ImageURL:     "https://placeholder.com/bracers.jpg",
			Tags:         []string{"armor", "leather", "accessories"},
			Rating:       4.3,
			ReviewCount:  67,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Steel Kite Shield",
			Model:        "SHD-005",
			SerialNumber: "SN-77665",
			Description:  "A large, teardrop-shaped shield ideal for deflecting arrows and cavalry charges.",
			Quantity:     0, // Out of stock edge case!
			Price:        150.00,
			Discount:     0,
			Warranty:     "1 Year",
			Distributor:  "Ironhelm Forge",
			Category:     "Apparel",
			ImageURL:     "https://placeholder.com/shield.jpg",
			Tags:         []string{"shield", "defense", "steel"},
			Rating:       4.5,
			ReviewCount:  41,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},

		// --- SPELLS & MAGIC ---
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Potion of Invisibility",
			Model:        "PTN-007",
			SerialNumber: "SN-11009",
			Description:  "Grants the drinker complete unseen status for exactly 3 minutes. Tastes like mint.",
			Quantity:     50,
			Price:        75.00,
			Discount:     0,
			Warranty:     "No Refunds",
			Distributor:  "The Arcane Order",
			Category:     "Spells",
			ImageURL:     "https://placeholder.com/invispotion.jpg",
			Tags:         []string{"potion", "stealth", "magic"},
			Rating:       4.8,
			ReviewCount:  203,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Wand of Fireballs",
			Model:        "WND-332",
			SerialNumber: "SN-99887",
			Description:  "A mahogany wand core-infused with a phoenix feather. Contains 50 charges.",
			Quantity:     5,
			Price:        850.00,
			Discount:     50.0,
			Warranty:     "Void if exposed to water",
			Distributor:  "The Arcane Order",
			Category:     "Spells",
			ImageURL:     "https://placeholder.com/wand.jpg",
			Tags:         []string{"magic", "fire", "ranged"},
			Rating:       4.2,
			ReviewCount:  19,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Minor Mana Potion",
			Model:        "PTN-002",
			SerialNumber: "SN-11011",
			Description:  "Restores a small amount of magical energy. Essential for apprentice mages.",
			Quantity:     200, // High stock edge case!
			Price:        10.00,
			Discount:     0,
			Warranty:     "No Refunds",
			Distributor:  "The Arcane Order",
			Category:     "Spells",
			ImageURL:     "https://placeholder.com/manapotion.jpg",
			Tags:         []string{"potion", "mana", "consumable"},
			Rating:       4.0,
			ReviewCount:  412,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Tome of Ancient Lore",
			Model:        "BOK-001",
			SerialNumber: "SN-55667",
			Description:  "A dusty, leather-bound book containing forgotten history and basic enchantments.",
			Quantity:     3,
			Price:        300.00,
			Discount:     0,
			Warranty:     "As-Is Condition",
			Distributor:  "Silvermoon Library",
			Category:     "Spells",
			ImageURL:     "https://placeholder.com/tome.jpg",
			Tags:         []string{"book", "lore", "magic"},
			Rating:       4.9,
			ReviewCount:  6,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},

		// --- ACCESSORIES & MISC ---
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Ring of Vitality",
			Model:        "RNG-010",
			SerialNumber: "SN-22334",
			Description:  "A silver band set with a ruby. Slightly increases the wearer's stamina.",
			Quantity:     14,
			Price:        220.00,
			Discount:     20.0,
			Warranty:     "Lifetime",
			Distributor:  "Shadow Traders",
			Category:     "Accessories",
			ImageURL:     "https://placeholder.com/ring.jpg",
			Tags:         []string{"jewelry", "enchanted", "health"},
			Rating:       4.6,
			ReviewCount:  45,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Crystal Ball of Scrying",
			Model:        "MIS-055",
			SerialNumber: "SN-33445",
			Description:  "Allows the user to glimpse faraway places. Requires intense concentration.",
			Quantity:     2,
			Price:        1200.00,
			Discount:     0,
			Warranty:     "No Warranty (Fragile)",
			Distributor:  "The Arcane Order",
			Category:     "Accessories",
			ImageURL:     "https://placeholder.com/crystalball.jpg",
			Tags:         []string{"magic", "divination", "tool"},
			Rating:       3.9,
			ReviewCount:  14,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Amulet of Protection",
			Model:        "AML-003",
			SerialNumber: "SN-77889",
			Description:  "Wards off minor curses and hexes. Glows faintly when danger is near.",
			Quantity:     0, // Out of stock edge case!
			Price:        450.00,
			Discount:     0,
			Warranty:     "5 Years",
			Distributor:  "Silvermoon Library",
			Category:     "Accessories",
			ImageURL:     "https://placeholder.com/amulet.jpg",
			Tags:         []string{"jewelry", "defense", "magic"},
			Rating:       4.7,
			ReviewCount:  28,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Lockpick Set",
			Model:        "MIS-009",
			SerialNumber: "SN-99001",
			Description:  "A 10-piece set of steel tools for opening standard chest and door locks.",
			Quantity:     40,
			Price:        35.00,
			Discount:     0,
			Warranty:     "30 Days",
			Distributor:  "Shadow Traders",
			Category:     "Accessories",
			ImageURL:     "https://placeholder.com/lockpick.jpg",
			Tags:         []string{"tools", "stealth", "rogue"},
			Rating:       4.4,
			ReviewCount:  132,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		models.Product{
			ID:           primitive.NewObjectID(),
			Name:         "Torch",
			Model:        "MIS-001",
			SerialNumber: "SN-11111",
			Description:  "A simple wooden stick wrapped in pitch-soaked rags. Burns for 1 hour.",
			Quantity:     500,
			Price:        2.00,
			Discount:     0,
			Warranty:     "No Warranty",
			Distributor:  "Woodland Fletchers",
			Category:     "Accessories",
			ImageURL:     "https://placeholder.com/torch.jpg",
			Tags:         []string{"tool", "light", "consumable"},
			Rating:       4.1,
			ReviewCount:  890,
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
	}

	// 5. Insert into MongoDB
	result, err := collection.InsertMany(ctx, mockProducts)
	if err != nil {
		log.Fatalf("Failed to insert mock data: %v", err)
	}

	log.Printf("Successfully seeded %d medieval products into MongoDB!\n", len(result.InsertedIDs))
}
